// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa0l-565m0BJs0YJaTXjjMssh-9VIItoU',
    appId: '1:785056268965:web:3651ac36a4e6751fa9434c',
    messagingSenderId: '785056268965',
    projectId: 'e-shtreeli-260422',
    authDomain: 'e-shtreeli-260422.firebaseapp.com',
    storageBucket: 'e-shtreeli-260422.appspot.com',
    measurementId: 'G-BZKCBBW2QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoE2lNWV04hF5Dkumi3q6MrMQWXWkFeg',
    appId: '1:785056268965:android:19328035a2a10d79a9434c',
    messagingSenderId: '785056268965',
    projectId: 'e-shtreeli-260422',
    storageBucket: 'e-shtreeli-260422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31dnNvXHgEKDaWOMZteWDuT_ZLHFjAAs',
    appId: '1:785056268965:ios:d103cfdff2fc2b74a9434c',
    messagingSenderId: '785056268965',
    projectId: 'e-shtreeli-260422',
    storageBucket: 'e-shtreeli-260422.appspot.com',
    iosBundleId: 'com.eshtreeli.shtreeli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31dnNvXHgEKDaWOMZteWDuT_ZLHFjAAs',
    appId: '1:785056268965:ios:eb8efea6800db67aa9434c',
    messagingSenderId: '785056268965',
    projectId: 'e-shtreeli-260422',
    storageBucket: 'e-shtreeli-260422.appspot.com',
    iosBundleId: 'com.example.eshtreeli_flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa0l-565m0BJs0YJaTXjjMssh-9VIItoU',
    appId: '1:785056268965:web:5b20947ee5d2dc71a9434c',
    messagingSenderId: '785056268965',
    projectId: 'e-shtreeli-260422',
    authDomain: 'e-shtreeli-260422.firebaseapp.com',
    storageBucket: 'e-shtreeli-260422.appspot.com',
    measurementId: 'G-0DFCF772CV',
  );
}
